sampler:
  which: nautilus
  n_livepoints: 10_000
  random_seed: 42
  run_kwargs:
    f_live: 0.001
    n_eff: 10_000

simulator:
  resolution: 1000
  time_limit: 15

parameters:
  C/O:
    true_value: 0.55
    action: condition
  Fe/H:
    true_value: 0.0
    action: condition
  P_quench:
    true_value: -5.0
    action: infer
  log_X_Fe:
    true_value: -0.86
    action: infer
  log_X_MgSiO3:
    true_value: -0.65
    action: infer
  f_sed:
    true_value: 3.0
    action: condition
  log_K_zz:
    true_value: 8.5
    action: condition
  sigma_g:
    true_value: 2.0
    action: infer
  log_g:
    true_value: 3.75
    action: condition
  R_P:
    true_value: 1.0
    action: condition
  T_0:
    true_value: 1063.6
    action: condition
  T_3/T_connect:
    true_value: 0.26
    action: infer
  T_2/T_3:
    true_value: 0.29
    action: infer
  T_1/T_2:
    true_value: 0.32
    action: infer
  alpha:
    true_value: 1.39
    action: infer
  log_delta/alpha:
    true_value: 0.48
    action: condition

htcondor:
  bid: 25
  n_cpus: 96
  memory: 100_000
  max_runtime: 21_600