#
# Configuration file for the cornerplot script.
#

# Results to include
results:
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/nested-sampling/nautilus/noise-free/sigma-0.125754/posterior.hdf"
    label: "nautilus"
    color: "#f3ac3f"
    use_weights: true
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/nested-sampling/multinest/noise-free/sigma-0.125754/posterior.hdf"
    label: "MultiNest"
    color: "#ba54a5"
    use_weights: true
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/fmpe/noise-conditional/importance_sampling/benchmark/noise-free/sigma-0.125754/results.min.hdf"
    label: "FMPE without IS"
    color: "#618df7"
    use_weights: false
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/fmpe/noise-conditional/importance_sampling/benchmark/noise-free/sigma-0.125754/results.min.hdf"
    label: "FMPE with IS"
    color: "#1e4bf1"
    use_weights: true
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/npe/noise-conditional/importance_sampling/benchmark/noise-free/sigma-0.125754/results.min.hdf"
    label: "NPE without IS"
    color: "#ec682d"
    use_weights: false
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/npe/noise-conditional/importance_sampling/benchmark/noise-free/sigma-0.125754/results.min.hdf"
    label: "NPE with IS"
    color: "#b93224"
    use_weights: true

# Parameters to include and ground truth values
parameters:
  C/O: 0.55
  Fe/H: 0.0
  log_P_quench: -5.0
  S_eq_Fe: -0.86
  S_eq_MgSiO3: -0.65
  f_sed: 3.0
  log_K_zz: 8.5
  sigma_g: 2.0
  log_g: 3.75
  R_P: 1.0
  T_int: 1063.0
  T_3: 0.26
  T_2: 0.29
  T_1: 0.32
  alpha: 1.39
  log_delta: 0.48

# General settings
dataset: "vasist_2023"
figsize: [17.5, 17.5]
fontsize_labels: 6.5
fontsize_ticks: 5.5
label_offset_x: -0.9
label_offset_y: -0.9
linewidth: 0.5
n_bins: 100
smoothing: 3
output_file_name: full-noise-free.pdf
