#
# Configuration file for the cornerplot script.
#

# Results to include
results:
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/nested-sampling/nautilus/with-noise/sigma-0.125754__0/posterior.hdf"
    label: "nautilus"
    color: "#F3AC3F"
    use_weights: true
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/nested-sampling/multinest/with-noise/sigma-0.125754__0/posterior.hdf"
    label: "MultiNest"
    color: "#BA54A5"
    use_weights: true
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/npe/noise-conditional/importance_sampling/benchmark/with-noise/sigma-0.125754__0/results.min.hdf"
    label: "NPE without IS"
    color: "#77C56D"
    use_weights: false
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/npe/noise-conditional/importance_sampling/benchmark/with-noise/sigma-0.125754__0/results.min.hdf"
    label: "NPE with IS"
    color: "#1E7B3E"
    use_weights: true
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/fmpe/noise-conditional/importance_sampling/benchmark/with-noise/sigma-0.125754__0/results.min.hdf"
    label: "FMPE without IS"
    color: "#699CFC"
    use_weights: false
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/fmpe/noise-conditional/importance_sampling/benchmark/with-noise/sigma-0.125754__0/results.min.hdf"
    label: "FMPE with IS"
    color: "#033696"
    use_weights: true

# Parameters to include and ground truth values
parameters:
  C/O: 0.55
  Fe/H: 0.0
  log_P_quench: -5.0
  S_eq_Fe: -0.86
  S_eq_MgSiO3: -0.65
  f_sed: 3.0
  log_K_zz: 8.5
  sigma_g: 2.0
  log_g: 3.75
  R_P: 1.0
  T_int: 1063.0
  T_3: 0.26
  T_2: 0.29
  T_1: 0.32
  alpha: 1.39
  log_delta: 0.48

# General settings
dataset: "vasist_2023"
figsize: [18.3, 18.3]
font_family: "Gillius ADF"
fontsize_labels: 8
fontsize_ticks: 6
label_offset_x: -0.9
label_offset_y: -0.9
linewidth: 0.75
n_bins: 100
smoothing: 3
output_file_name: full-with-noise.pdf
subplots_adjust:
  left: 0.07
  right: 0.999
  bottom: 0.07
  top: 0.999