#
# Configuration file for P-P plots
#

# Results to include (note: P-P plots only work for the default test set)
results:
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/npe/noise-conditional/importance_sampling/test-default/aggregated__test-default_X.hdf"
    n_retrievals: 500
    label: "NPE"
    color: "#77C56D"
  - file_path: "$FM4AR_EXPERIMENTS_DIR/paper/fmpe/noise-conditional/importance_sampling/test-default/aggregated__test-default_X.hdf"
    n_retrievals: 500
    label: "FMPE"
    color: "#699CFC"

# General plot settings
add_p_values: false
dataset: "vasist_2023"
figsize: [4.3, 4.0]
font_family: "Gillius ADF"
fontsize_labels: 8
fontsize_ticks: 6
subplots_adjust:
  bottom: 0.19
  top: 0.995
  left: 0.25
  right: 0.97